[build]
    base = 'Project-I-Social-Card/social-card/build'
    publish = 'Project-I-Social-Card/social-card/build'
    command = 'yarn start'
[build.environment]
    YARN_FLAGS = '--no-ignore-optional'